name: Terraform Workflow

on:
  push:
    branches: [ main ]

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.x

      - name: Initialize Terraform workspace
        run: terraform init

  validate:
    runs-on: ubuntu-latest
    needs: terraform-init
    steps:
      - uses: actions/checkout@v3
      - name: Validate infrastructure configuration
        run: terraform validate

  plan:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v3
      - name: Create Terraform plan
        run: terraform plan -out=planfile

  apply:
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - uses: actions/checkout@v3
      - name: Apply Terraform plan (manual approval required)
        run: terraform apply -input=false planfile

  destroy:
    runs-on: ubuntu-latest
    needs: apply
    steps:
      - uses: actions/checkout@v3
      - name: Destroy infrastructure (manual approval required)
        run: terraform destroy --auto-approve
        if: github.event.inputs.destroy 