name: Build - Test - Plan (Auto)

on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

  # test:
  #   runs-on: ubuntu-latest
  #   needs: validate
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Set up Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: 1.6

  #     - name: Terraform Init
  #       run: terraform init

  #     - name: Terraform Test
  #       run: terraform test

  plan:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=planfile

      - name: Upload Planfile as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-planfile
          path: planfile
