name: Terraform Workflow

on:
  push:
    branches: [ main ]

env:
  global:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: us-east-1

jobs:
  setup-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use HashiCorp Terraform action
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.x  

      - name: Initialize Terraform
        run: terraform init

  validate:
    runs-on: ubuntu-latest
    needs: setup-terraform
    steps:
      - uses: actions/checkout@v3

      - name: Validate Terraform configuration
        run: terraform validate

  plan:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v3

      - name: Create Terraform plan
        run: terraform plan -out=planfile

  apply:
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - uses: actions/checkout@v3

      - name: Apply Terraform plan
        run: terraform apply -input=false planfile
        env:
          TF_IN_AUTOMATION: true

  destroy:
    runs-on: ubuntu-latest
    needs: [ apply, ! main ]
    steps:
      - uses: actions/checkout@v3

      - name: Destroy Terraform resources
        run: terraform destroy --auto-approve