name: Terraform Pipeline

on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0 

      - name: Cache Terraform modules
        uses: actions/cache@v3
        with:
          path: ~/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('.terraform') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Create Terraform plan (optional)
        id: create-plan
        run: terraform plan -out=planfile
        when: needs.validate.outputs == 'success' 

      - name: Upload plan for review (optional)
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: planfile
        when: needs.create-plan.outputs == 'success' 

      - name: Apply Terraform changes (manual approval required)
        id: apply-changes
        run: terraform apply -input=false planfile
        needs: [ validate, create-plan ] 
        when: github.event.inputs.apply == 'true'  

      - name: Destroy Terraform resources (manual approval required)
        id: destroy-resources
        run: terraform destroy --auto-approve
        when: github.event.inputs.destroy == 'true'  